### ISSUE TITLE
Некорректно работают GET параметры типа array с style=form и explode = true

### ISSUE THREAD

**Issue by orlyk-rollun** [rollun-com/rollun-openapi#26]
В случае передачи параметра вида

```php
$client->get([
    'id' => [1,2,3]
]);
```

строка запроса выглядит следующим образом '0=21-07142-82213&1=17-07143-13568&2=05-07145-38679'.
Соответственно, при разборе на стороне сервера параметр numbers не определяется.

Согласно [спецификации](https://swagger.io/docs/specification/serialization/#query), если style = form и explode = true, строка запроса должна выглядить следущим образом ?id=1&id=2&id=3

**Comment by misha-rollun** [comment]
Пример из описания и не должен работать. Правильная передача параметра должна выглядеть так:

```php
/** @var \OpenAPI\Server\Rest\RestInterface $client */
$client->get(['id' => ['id' => [1, 2, 3]]]);
```

Зачем так сделано можно почитать тут: https://github.com/OpenAPITools/openapi-generator/pull/3984/files#r351831130

Тем не менее даже при передачи в правильном виде программа работает некорректно. Я на данный момент обнаружил следующие проблемы:
1. Неправильная обработка на стороне сервера: query вида ```id=1&id=2&id=3``` превращается в массив ```['id' => 1]```

2. На стороне клиента не правильно сформируется query. Перед тем как отправить запрос нужно сериализовать массив в строку. Пример того, как может происходить сериализация: https://github.com/OpenAPITools/openapi-generator/blob/870ef3a87ac5a9751198ea0f0e36c821563b5e61/modules/openapi-generator/src/main/resources/php/api.mustache#L496 (Я не изучал детально этот пример, так что возможно он и не подходит).

3. Не проходит валидация через DTO. Рассмотрим метод get сгенерированного Rest объект клиента:

```php
public function get($queryData = [])
{
    // validation of $queryData
    if ($queryData instanceof \HelloUser1\OpenAPI\V1\DTO\User1GETQueryData) {
        $queryData = $this->toArray($queryData);
    }
    $queryDataObject = $this->transfer((array)$queryData, '\HelloUser1\OpenAPI\V1\DTO\User1GETQueryData');

    // send request
    $data = $this->getApi()->user1Get($queryDataObject->id);

    // validation of response
    $result = $this->transfer((array)$data, \HelloUser1\OpenAPI\V1\DTO\UserResult::class);

    return $result;
}

/**
 * Query parameters for user1GET
 */
class User1GETQueryData
{
    /**
     * @DTA\Data(field="id", nullable=true)
     * TODO check validator and strategy are correct and can handle container item type
     * @DTA\Strategy(name="QueryParameterArray", options={"type":"string", "format":"multi"})
     * @DTA\Validator(name="QueryParameterArrayType", options={"type":"string", "format":"multi"})
     * @var string[]
     */
    public $id;
}
```

Как видно в методе GET происходит валидация через DTO `User1GETQueryData`, где 'id' должен быть массивом строк. Но мы передаем queryData в виде ```['id' => ['id' => [1, 2, 3]]]``` (в начале объяснено зачем) и валидация не проходит.

**Comment by orlyk-rollun** [comment]
Это очень странно, если передавать нужно ['id' => ['id' => [1, 2, 3]]] когда мне нужно передать [id = [1, 2, 3]]. И что такая передача параметра правильная, мне кажется, утверждение сомнительное. По указанной ссылке я не нашел убедительного обьяснения почему так долно быть и вообще, что так нужно передавать параметры с дублированием ключа. @misha-rollun можешь пальцем показать, пожалуйста, где такое написано?

**Comment by orlyk-rollun** [comment]
В общем, я это поправил. Работает передача параметров со стороны клиентска ['id' => [1, 2, 3]] при style = form и explode = true. Формируется строка запроса согласно спецификации id=1&id=2&id=3.
На серверной стороне добавил парсинг такой строки с преобразованием в массив.
Коммит https://github.com/rollun-com/rollun-openapi/commit/6a2cd5e4e703f9ec87de7588dc63a49c3fd76d3b

**Comment by orlyk-rollun** [comment]
В общем, я это поправил. Работает передача параметров со стороны клиентска ['id' => [1, 2, 3]] при style = form и explode = true. Формируется строка запроса согласно спецификации id=1&id=2&id=3.
На серверной стороне добавил парсинг такой строки с преобразованием в массив.
Коммит https://github.com/rollun-com/rollun-openapi/commit/6a2cd5e4e703f9ec87de7588dc63a49c3fd76d3b
